version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
        name: docker-compose up
        command: |
          docker-compose up -d
          docker run --network host \
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:4000
